
CREATE DATABASE WPF_JUEGOS

CREATE TABLE JUEGO(

	ID INT PRIMARY KEY,
	Nombre VARCHAR(100),
	Descripcion VARCHAR(300),
	ReleaseYear SMALLDATETIME,
	Rating INT,
	img VARCHAR(400),
	Genre_ID INT,
	Platform_ID INT,

	CONSTRAINT PK_ID_JUEGO PRIMARY KEY (ID),
	CONSTRAINT FK_JUEGO_GENRE FOREIGN KEY (Genre_ID) REFERENCES GENRE(ID_Genre),
    CONSTRAINT FK_JUEGO_PLATFORM FOREIGN KEY (Platform_ID) REFERENCES GAME_PLATFORM(Platform_ID)
	);


CREATE TABLE GENRE(

	ID_Genre INT,
	Name_genres VARCHAR(100)

	CONSTRAINT PK_Genre_ID_GENRE PRIMARY KEY (ID_Genre)
	);


CREATE TABLE GAME_PLATFORM(

	Platform_ID INT,
	Name_Platform VARCHAR(100)

	CONSTRAINT PK_Platform_ID PRIMARY KEY (Platform_ID)
	);

-------------------------------------------------------------------------
CREATE DATABASE WPF_JUEGOS;

CREATE TABLE USUARIO (
    ID INT PRIMARY KEY,
    Nombre VARCHAR(100),
    Email VARCHAR(100),
    Password VARCHAR(100)
);

CREATE TABLE GENERO (
    ID_Genre INT PRIMARY KEY,
    Name_genres VARCHAR(100)
);

CREATE TABLE DESARROLLADOR (
    ID_Developer INT PRIMARY KEY,
    Name_Developer VARCHAR(100)
);

CREATE TABLE PLATAFORMA (
    Platform_ID INT PRIMARY KEY,
    Name_Platform VARCHAR(100)
);

CREATE TABLE JUEGO (
    ID INT PRIMARY KEY,
    Nombre VARCHAR(100),
    Descripcion VARCHAR(300),
    ReleaseYear SMALLDATETIME,
    Rating INT,
    img VARCHAR(400),
    Genre_ID INT,
    Developer_ID INT,
    User_ID INT,
    Price DECIMAL(10, 2),
    PurchaseDate SMALLDATETIME,
    CompletionDate SMALLDATETIME,
    Status VARCHAR(50), -- Campo para el estado del juego
    CONSTRAINT FK_JUEGO_GENRE FOREIGN KEY (Genre_ID) REFERENCES GENRE(ID_Genre),
    CONSTRAINT FK_JUEGO_DEVELOPER FOREIGN KEY (Developer_ID) REFERENCES DEVELOPER(ID_Developer),
    CONSTRAINT FK_JUEGO_USUARIO FOREIGN KEY (User_ID) REFERENCES USUARIO(ID)
);

CREATE TABLE JUEGO_PLATAFORM (
    Juego_ID INT,
    Platform_ID INT,
    CONSTRAINT PK_JUEGO_PLATAFORM PRIMARY KEY (Juego_ID, Platform_ID),
    CONSTRAINT FK_JUEGO_PLATAFORM_JUEGO FOREIGN KEY (Juego_ID) REFERENCES JUEGO(ID),
    CONSTRAINT FK_JUEGO_PLATFORM_PLATAFORM FOREIGN KEY (Platform_ID) REFERENCES PLATAFORMA(Platform_ID)
);